﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace EvAlmak
{
    public partial class MLModel1
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Size", @"Size"),new InputOutputColumnPair(@"Bath", @"Bath"),new InputOutputColumnPair(@"Balcony", @"Balcony"),new InputOutputColumnPair(@"Floor", @"Floor")})      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Chimney", @"Chimney"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Fitness", @"Fitness"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Size",@"Bath",@"Balcony",@"Floor",@"Chimney",@"Fitness"}))      
                                    .Append(mlContext.Regression.Trainers.FastTree(new FastTreeRegressionTrainer.Options(){NumberOfLeaves=4,MinimumExampleCountPerLeaf=13,NumberOfTrees=4,MaximumBinCountPerFeature=121,LearningRate=0.0364712285744316F,FeatureFraction=0.919689084468668F,LabelColumnName=@"Price",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
