﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace EvAlmak
{
    public partial class MLModel1
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Floor", @"Floor"),new InputOutputColumnPair(@"Size", @"Size"),new InputOutputColumnPair(@"Bath", @"Bath"),new InputOutputColumnPair(@"Balcony", @"Balcony"),new InputOutputColumnPair(@"NumberOfChimney", @"NumberOfChimney")})      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Direction", @"Direction"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Sauna", @"Sauna"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Chimney", @"Chimney"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Fitness", @"Fitness"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Floor",@"Size",@"Bath",@"Balcony",@"NumberOfChimney",@"Direction",@"Sauna",@"Chimney",@"Fitness"}))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.Regression.Trainers.Sdca(l1Regularization:0.465632903335694F,l2Regularization:0.519472102781485F,labelColumnName:@"Price",featureColumnName:@"Features"));

            return pipeline;
        }
    }
}
